# ========================
# Model & Paths
# ========================
base_model: $STORAGE_ROOT/apertus/huggingface/Apertus8B
output_dir: $STORAGE_ROOT/meditron/models/Meditron-Apertus-8B-xav-no-completion

dataset_prepared_path: $USER_STORAGE/prepared/Meditron-Apertus-8B-xav-no-completion
load_prepared_dataset: true

wandb_name: Meditron-Apertus-8B-xav-no-completion

# ========================
# Hardware & Speed
# ========================
deepspeed: $PROJECT_ROOT/axolotl_config/deepspeed_zero_2.json
bf16: auto
tf32: false # SHOULD be true
flash_attention: true
flash_attn_rms_norm: true
flash_attn_fuse_qkv: false
xformers_attention: null
strict: false

# ========================
# Datasets
# ========================
chat_template: tokenizer_default
datasets:
  # -- Chat Datasets (Shared Config) --
  - &chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00001.jsonl
    ds_type: json
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
    roles:
      system: [system]
      user: [user, human]
      assistant: [assistant, gpt]

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00002.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00003.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00004.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00005.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00006.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00007.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00008.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00009.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl.part-00010.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/meadow/meadow.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/medqa/medqa.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/medtext/medtext.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/pubmedqa/pubmedqa.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/medmcqa/medmcqa.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/wikidoc_qa/wikidoc_qa.jsonl


dataset_processes: 128
shuffle_merged_datasets: true

# ========================
# Training Hyperparameters
# ========================
type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
sequence_len: 4096
sample_packing: true # SHOULD be true
pad_to_sequence_len: true
group_by_length: false
train_on_inputs: false

num_epochs: 1
micro_batch_size: 4
gradient_accumulation_steps: 8
max_grad_norm: 1.0

# ========================
# Optimization
# ========================
optimizer: adamw_torch
optim_args:
  fused: true
learning_rate: 1.0e-5
lr_scheduler: cosine
cosine_min_lr_ratio: 0.1
warmup_ratio: 0.03 #SHOULD have a warmup eg 0.3
weight_decay: 0.05

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# ========================
# Quantization (Disabled)
# ========================
load_in_4bit: false
load_in_8bit: false

# ========================
# Logging & Evaluation
# ========================
logging_steps: 1
saves_per_epoch: 1
evals_per_epoch: 1 #SHOULD be 4
eval_set_size: 0.001 # SHOULD be 0.01
eval_table_size: null
early_stopping_patience: null

wandb_project: $WANDB_PROJECT
wandb_entity: $WANDB_ENTITY