# ========================
# Model & Paths
# ========================
base_model: $STORAGE_ROOT/apertus/huggingface/Apertus8B
output_dir: $STORAGE_ROOT/meditron/models/Meditron-Apertus-8B-xav-trad-1e-6

dataset_prepared_path: $USER_STORAGE/prepared/meditron-apertus-xav-trad
load_prepared_dataset: true

wandb_name: Meditron-Apertus-8B-xav-trad-1e-6

# ========================
# Hardware & Speed
# ========================
deepspeed: $PROJECT_ROOT/axolotl_config/deepspeed_zero_2.json
bf16: auto
tf32: false 
flash_attention: true
flash_attn_rms_norm: true
flash_attn_fuse_qkv: false
xformers_attention: null
strict: false

# ========================
# Datasets
# ========================
chat_template: tokenizer_default
datasets:
  # -- Chat Datasets (Shared Config) --
  - &chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/miriad/miriad-4.4M.jsonl
    ds_type: json
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
    roles:
      system: [system]
      user: [user, human]
      assistant: [assistant, gpt]

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/meadow/meadow.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/medqa/medqa.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/medtext/medtext.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/pubmedqa/pubmedqa.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/medmcqa/medmcqa.jsonl

  - <<: *chat_config
    path: $STORAGE_ROOT/meditron/datasets/masked/wikidoc_qa/wikidoc_qa.jsonl

  # -- Completion Datasets --
  - path: $STORAGE_ROOT/meditron/datasets/pretrain/guidelines/guidelines.jsonl
    ds_type: json
    type: completion
    field: text

  - path: $STORAGE_ROOT/meditron/datasets/pretrain/pubmed/pubmed_3B.jsonl
    ds_type: json
    type: completion
    field: text

dataset_processes: 64
shuffle_merged_datasets: true

# ========================
# Training Hyperparameters
# ========================
type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
sequence_len: 8192
sample_packing: true # SHOULD be true
pad_to_sequence_len: true
group_by_length: false
train_on_inputs: false

num_epochs: 1
micro_batch_size: 2
gradient_accumulation_steps: 16
max_grad_norm: 1.0

# ========================
# Optimization
# ========================
optimizer: adamw_torch
optim_args:
  fused: true
learning_rate: 1.0e-6
lr_scheduler: cosine
cosine_min_lr_ratio: 0.1
warmup_ratio: 0.03 
weight_decay: 0.05

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# ========================
# Quantization (Disabled)
# ========================
load_in_4bit: false
load_in_8bit: false

# ========================
# Logging & Evaluation
# ========================
logging_steps: 1
saves_per_epoch: 1
evals_per_epoch: 1 
eval_set_size: 0.001 
eval_table_size: null
early_stopping_patience: null

wandb_project: $WANDB_PROJECT
wandb_entity: $WANDB_ENTITY